/**
 * ARCO Daily Planning Script
 * Generates daily plan with strategic context for focused work
 */

import { SimpleContextManager } from '../src/lib/simple-context-manager'
import fs from 'fs/promises'
import path from 'path'

async function generateDailyPlan(): Promise<void> {
  const manager = new SimpleContextManager()
  const today = new Date().toLocaleDateString('pt-BR')
  
  console.log('🌅 Generating ARCO Daily Plan...')
  
  // Get strategic contexts
  const prioritiesContext = await manager.getContextFor("What are today's priorities?")
  const blockersContext = await manager.getContextFor("What blockers should I address?")
  const businessContext = await manager.getContextFor("What business goals drive today's work?")
  
  const dailyPlan = `# ARCO Daily Plan - ${today}

## 🎯 Strategic Context
${businessContext}

## 📋 Priorities Context  
${prioritiesContext}

## 🚧 Blockers & Constraints Context
${blockersContext}

---

## 📝 Today's Action Items
- [ ] **Priority 1 (High Impact):** ___
- [ ] **Priority 2 (Business Critical):** ___
- [ ] **Priority 3 (Technical Debt):** ___

## 💼 Business Impact Goals
- [ ] **Client Work Quality:** ___
- [ ] **Sales Conversation Prep:** ___  
- [ ] **Platform Development:** ___

## 🔄 Context Integration Checkpoints
- [ ] **Morning:** Review priorities with context
- [ ] **Midday:** Check alignment with business goals
- [ ] **Evening:** Assess progress and blockers

## 📊 Decision Support Queries (Use throughout day)
\`\`\`bash
# For technical decisions
npm run context:query "Should I implement X or optimize Y?"

# For business decisions  
npm run context:query "How does this align with ARCO positioning?"

# For priority decisions
npm run context:query "What's the highest ROI task right now?"
\`\`\`

---

## 🎯 Success Criteria for Today
- [ ] Made decisions using context system
- [ ] Maintained business-first focus
- [ ] Advanced client work quality
- [ ] Prepared for sales opportunities
- [ ] Reduced context switching time

**End of Day:** Review what worked, what didn't, adjust tomorrow's approach.

---
*Generated by ARCO Context System - ${new Date().toLocaleString('pt-BR')}*
`

  // Save to file
  const planPath = path.join(process.cwd(), `daily-plans`, `daily-plan-${today.replace(/\//g, '-')}.md`)
  await fs.mkdir(path.dirname(planPath), { recursive: true })
  await fs.writeFile(planPath, dailyPlan)
  
  console.log('✅ Daily plan generated!')
  console.log(`📄 Saved to: ${planPath}`)
  console.log('\n📋 Today\'s Focus Areas:')
  console.log('1. Client work and business development (80%)')
  console.log('2. Context system integration (15%)')
  console.log('3. System maintenance (5%)')
  console.log('\n🚀 Use: npm run context:query "your question" throughout the day')
}

// Run if called directly
if (require.main === module) {
  generateDailyPlan().catch(console.error)
}

export { generateDailyPlan }
